### ISSUE TITLE
How to sequentially show tap targets that are in different target scopes?

### ISSUE THREAD

**Issue by nicoqueijo** [PierfrancescoSoffritti/tap-target-compose#7]
Is there a way to sequentially show tap targets that are in different target scopes? 
For example, I have a screen (red) which contains a FAB (blue) and a list of items (yellow). Each list item is a separate Composable in the list of items and one of its elements is a Text (purple).

I am trying to have a tap target show up for the FAB (blue) first and then for the Text (purple) second. But I'm not sure how to do that since they are not in the same Composable so I can't wrap them both in a single `TapTargetCoordinator`.

An idea that came up was to initialize a `TapTargetCoordinatorState` in the screen composable, use it for the FAB, and pass it down to the list items but I can't do so because `TapTargetCoordinatorState` has an internal constructor. Any idea how to solve this?

![image](https://github.com/PierfrancescoSoffritti/tap-target-compose/assets/20692755/beb5b414-6cf8-4e17-b6a5-f8c10c586c22)

**Comment by PierfrancescoSoffritti** [comment]
Hey, currently it's not possible to coordinate targets in different scopes. Why can't you use the same scope for both?

For example: 

```kotlin
@Composable
fun Parent() {
  TapTargetCoordinator() {
    Component1()
    Component2()
  }
}

@Composable
fun TapTargetScope.Component1() {
  Text("hello", modifier = Modifier.tapTarget(precedence = 0))
}

@Composable
fun TapTargetScope.Component2() {
    Text("world", modifier = Modifier.tapTarget(precedence = 1))
}
```

**Comment by nicoqueijo** [comment]
I was thinking because I have the Screen and Row in different files and I am trying to target a specific element within the Row, not the entire Row. I'll try again and see if I can get it to work. Thanks!

**Comment by PierfrancescoSoffritti** [comment]
Ok, it should work by passing around the `TapTargetScope`. But I understand that it's not the most convenient API.

**Comment by nicoqueijo** [comment]
I got it to work, thanks!

**Comment by PierfrancescoSoffritti** [comment]
Glad to hear :)
